//
//  StatementModels.swift
//  Assignment
//
//  Created by Digvijay Joshi on 23/10/19.
//  Copyright (c) 2019 Digvijay Joshi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Statement
{

	enum FetchStatement
  {
    struct Request
    {
    }
		struct Response:Codable
		{
			var title: String
			var desc: String
			var date: String
			var value: Double
		}
    struct ViewModel
    {
			struct Transaction: Equatable {
				var title: String
				var desc: String
				var date: String
				var value: Double
			}
			var displayedTransactions: [Transaction]
    }
  }
	
	enum GetUserAccount
	{
		struct Request
		{
		}
		struct Response
		{
			var userAccount: UserAccount
		}
		struct ViewModel
		{
			var displayedUser : UserAccount
		}
		
	}
	
}
