//
//  LoginInteractor.swift
//  Assignment
//
//  Created by Digvijay Joshi on 26/10/19.
//  Copyright (c) 2019 Digvijay Joshi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func loginProcess(request: Login.LoginUser.Request)
}

protocol LoginDataStore
{
  var userAccount: UserAccount? { get }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
	var userAccount: UserAccount?
	
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
	
  
  // MARK: Login Process
  
  func loginProcess(request: Login.LoginUser.Request)
  {
    worker = LoginWorker()
		worker?.loginUser(completion: { (response , error) in
			if let responseData = response {
				self.userAccount = UserAccount(bankAccount: responseData.bankAccount,
																	agency: responseData.agency,
																	userId: responseData.userId,
																	name: responseData.name,
																	balance: responseData.balance)
				self.presenter?.presentStatementView(response: responseData)
			} else{
				Utility.displayAlert(title: "Network Error", message: error!.localizedDescription)
			}
		})
  }
	
}
