//
//  LoginPresenter.swift
//  Assignment
//
//  Created by Digvijay Joshi on 26/10/19.
//  Copyright (c) 2019 Digvijay Joshi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentStatementView(response: Login.LoginUser.Response)
	
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Navigate to Statement View
  
	func presentStatementView(response: Login.LoginUser.Response)
  {
		let response = response.self
		
		let userAccountDetail = Login.LoginUser.ViewModel.UserAccount(bankAccount: response.bankAccount,
																														agency: response.agency,
																														userId: response.userId,
																														name: response.name,
																														balance: response.balance)
		let userAccountViewModel = Login.LoginUser.ViewModel(userAccount: userAccountDetail)
    viewController?.presentStatmentView(viewModel: userAccountViewModel)
  }
}
